### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by BelenRodriguezSchachtschneider** [algo1unsam/presentacion-personal-caroopa#1]
Hola Carolina! Yo quizás sacaría del post lo de "Ya no sé qué más decir." como para que te quede mejor el texto. Igualmente es solo un comentario para poder cumplir con la segunda parte del TP 0.

**Comment by caroopa** [comment]
Lo había puesto para meter un poco de humor (soy malísima para presentarme) pero se ve que no funcionó jajaja. Ahí lo saco.
